sudo: false
language: node_js
node_js:
  - "8"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  fqdn: muniranians.com
  on:
    branch: master